language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install tox
script:
  - tox
  - python setup.py bdist_wheel
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: dist/*.whl
    file_glob: true
    skip_cleanup: true
    skip_upload_docs: true
    on:
      tags: true
  - provider: pypi
    user: bwanamarko
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel" # Your distributions here
    skip_upload_docs: true
    on:
      tags: true
